name:                HRubik
version:             0.1.0.0
author:              "hectorg87"
copyright:           "2016 hectorg87"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nwtgck/HRubik#readme>

dependencies:
- base >= 4.7 && < 5

#library:
#  source-dirs: src

executables:
  HRubik:
    main:                HRubik.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - containers
    - GLUT
    - QuickCheck 

tests:
  HRubik-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HRubik
